[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'src/test'
remappings = [
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
]

verbosity = 2

# Solidity optimizer
# optimizer = true
# optimizer_runs = 20_000
# via_ir = true

# See more config options https://github.com/gakonst/foundry/tree/master/config
